#-------------------------------
# General Site Settings

title: Ramadhan Aheebwa's Online Place
description: I'm Aheebwa Ramadhan Badr, a Ugandan-based freelance developer. I craft lines of code into user friendly, beautiful, multi-functional and mostly importantly easy to use applications for the web , mobile and desktop. My main stacks are PHP/Laravel and Ruby/Rails among many others. As both an engineer and designer I help people bring their ideas into reality (My Work), as I craft them uniquely to their preferences. Contact Me today, I would be glad to hear from you. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://raheebwa.com" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Aheebwa Ramadhan
author-avatar: 09.jpg


#-------------------------------
# Contact links
facebook:  https://facebook.com/badrama213 # Add your Facebook handle
twitter:   https://twitter.com/raheebwa # Add your Facebook handle
instagram: https://www.instagram.com/raheebwa90 # Add your Facebook handle
# pinterest: https://www.pinterest.com/ # Add your Facebook handle


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: ramadhanaheebwa # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: UA-147514520-1 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: https://raheebwa.us4.list-manage.com/subscribe/post?u=e74dc7ba0ae22a4d02a3a40e6&amp;id=fc8bbb3ede # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
